# Generated by Django 6.0.8 on 2026-08-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('extended_attributes', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.TextField()),
                ('level', models.PositiveIntegerField(default=0)),
                ('vertical', models.CharField(blank=True, max_length=255)),
                ('vertical_prefix', models.CharField(blank=True, max_length=50)),
                ('attributes', models.ManyToManyField(blank=True, related_name='categories', to='taxonomy.shopifyattribute')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='taxonomy.shopifycategory')),
            ],
        ),
        migrations.CreateModel(
            name='ShopifyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('handle', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='taxonomy.shopifyattribute')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attribute', 'handle'), name='unique_attribute_value_handle')],
            },
        ),
    ]
