# Generated by Django 6.0.8 on 2026-08-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(max_length=100, unique=True)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('bullets', models.TextField(blank=True)),
                ('set_includes', models.TextField(blank=True)),
                ('product_category', models.CharField(blank=True, max_length=200)),
                ('product_sub_category', models.CharField(blank=True, max_length=200)),
                ('collection_name', models.CharField(blank=True, max_length=200)),
                ('color_collection', models.CharField(blank=True, max_length=100)),
                ('product_color', models.CharField(blank=True, max_length=200)),
                ('materials', models.CharField(blank=True, max_length=500)),
                ('product_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('product_dimensions', models.TextField(blank=True)),
                ('assembly_required', models.CharField(blank=True, max_length=20)),
                ('is_a_set', models.CharField(blank=True, max_length=20)),
                ('stackable', models.CharField(blank=True, max_length=20)),
                ('country_of_origin', models.CharField(blank=True, max_length=100)),
                ('item_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('map_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('msrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('image_urls', models.JSONField(blank=True, default=list)),
                ('shipping_method', models.CharField(blank=True, max_length=100)),
                ('total_box_count', models.IntegerField(blank=True, null=True)),
                ('pallet_count', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_cbm', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('package_dimensions', models.TextField(blank=True)),
                ('product_url', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
