# Generated by Django 6.0.8 on 2026-08-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productclassification'),
    ]

    operations = [
        migrations.AddField(
            model_name='productclassification',
            name='alternatives',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productclassification',
            name='attributes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productclassification',
            name='status',
            field=models.CharField(default='manual_review', max_length=30),
        ),
    ]
